### ISSUE TITLE
Any way to encode columns?

### ISSUE THREAD

**Issue by wmcraver** [marcschwartz/WriteXLS#10]
I've written a script that exports two sheets.  Each sheet has a column of dates that, in the data frame, are stored as date, but when written to Excel are formatted as text.  Is there any way around this?

**Comment by marcschwartz** [comment]
Hi,

The data frames are exported from R to intermediate CSV files which, of course, retain no concept of data types.

The CSV files are then parsed using the Perl scripts to create the worksheets in the Excel file and the data are written using the default "General" format. Thus, none of the columns are created using column specific data types such as Text, Dates, Numeric, Currency, Time, etc.

The intent of the WriteXLS package is primarily to facilitate the transfer of bulk data from R data frames to another party using Excel files, where that is a convenient file format to do so. That is derived from my own experience over the years with clients who prefer that vehicle for various reasons, when sending large amounts of data.

Thus, there is no cell level formatting, cell borders, data typing or other functionality that is supported, other than bolding the header row and adjusting column widths for cell text width, which are primarily to ease the visual reading of the data in the worksheet.

There was no intent to facilitate further manipulation of the data in the Excel worksheet itself (e.g. using formulae or other Excel specific functions) that might depend upon specific data types or cell formatting.

If you only have a limited number of columns that are affected, you could manually adjust the data type for the relevant columns in Excel by highlighting the column, except the header cell and adjusting the cell formatting for that column.

Alternatively, you could just export the data frames from R to CSV files, using ?write.csv, then use the Excel Import functionality, which will then adjust column data types based upon the imported data.

Other than that, if this is something where manual "post processing" of the Excel worksheets is going to be cumbersome and time consuming for you, you might want to look at one of the other CRAN packages that facilitate exporting data from R to Excel, like XLConnect or similar.

Regards,

Marc

**Comment by wmcraver** [comment]
Thanks, Marc.  I've got an RScript on a schedule that runs daily.  My colleague has a database that reads that Excel file.  She's built a workaround for the dates, I was just trying to see if there was another way around it with the package.  

By the way, I just discovered your package and love it!  Great work!

**Comment by marcschwartz** [comment]
Hi Mitch,

Glad that you have an alternative option in your workflow.

I appreciate your kind comments! Thanks!

Regards,

Marc
