### ISSUE TITLE
Numeric values are written as strings with WriteXLS 6.0.0

### ISSUE THREAD

**Issue by stibu81** [marcschwartz/WriteXLS#18]
With WriteXLS 6.0.0, some values in numeric columns are written as strings instead of numbers. This did not happen with WriteXLS 5.0.0.

WriteXLS 5.0.0 is running with perl v5.26.1 on Ubuntu 18.04.5, WriteXLS 6.0.0 with perl v5.30.0 on Ubuntu 20.04.1.

## Reproducible example

The following code was used to write an Excel-file with WriteXLS 5.0.0 and 6.0.0:

```
data <- tibble::tibble(
    x = sample(letters, 1000, replace = TRUE),
    y = sample(1000:9999, 1000, replace = TRUE))
WriteXLS::WriteXLS(data, "/media/exchange/tmp/test_writexls.xlsx")
```

The resulting files are attached:
[test_writexls5.xlsx](https://github.com/marcschwartz/WriteXLS/files/5508748/test_writexls5.xlsx)
[test_writexls6.xlsx](https://github.com/marcschwartz/WriteXLS/files/5508750/test_writexls6.xlsx)

A screenshot shows the problem:

![writexls](https://user-images.githubusercontent.com/7131000/98513115-a7f8ac00-2267-11eb-9815-233655444983.png)

**Comment by marcschwartz** [comment]
Hi,

Thanks for the detailed information.

There is newly documented behavior in version 6.0.0. Per ?WriteXLS:

"Values containing leading and/or trailing zeroes in data frame content will be treated, by default, as text, such that these zeroes will be preserved in the Excel worksheet content, rather than being coerced to numeric values and being stripped, which is the default Excel behavior. These values will be left-justified in the cells, rather than being right-justified, and there may be a mix of justification in a single column, based upon the data present."

and there is at least one example in ?WriteXLS that demonstrates this.

That being said, I created a regular R data frame, along the lines of what you have above, and you can see that in the case of "integer" values, the trailing zero is both preserved and the cell is right justified. See the attached screen capture:

<img width="153" alt="Screen Shot 2020-11-09 at 2 32 00 PM" src="https://user-images.githubusercontent.com/1749084/98587838-b7dcb400-2298-11eb-8832-fe9294f2bfc4.png">

I do not use the Tidyverse, but I am going to hazard a guess that there is something about the way that a tibble is stored that is creating the issue, through some kind of interaction with the exporting process.

Since WriteXLS is not intended to support tibbles, and only standard R data frames, this is not something that I will address, unless you can demonstrate an example of similar behavior with default R data frames. The prior behavior with version 5.0.0 of WriteXLS may have, purely by coincidence, not exhibited this with tibbles, not by intent or testing.

**Comment by stibu81** [comment]
Thanks for your reply. Thanks to your hint regarding the trailing zeroes I managed to create a better reproducible example. Interestingly, the trailing zeroes seem not to be enough, but some configurations of zeroes to lead to numbers being formatted as text. This happens with data frames as well. Because it only happens for very specific numbers, you accidentally did not have any of those in your example.

But this data frame contains numbers that are formatted as text:

    data <- data.frame(x = letters[1:4], y = c(2800, 3050, 10230, 2000))
    WriteXLS(data, "test.xlsx")

This is how it looks (in LibreOffice because I don't have access to Excel right now):

![example_data_frame](https://user-images.githubusercontent.com/7131000/98594359-d660a080-22d4-11eb-9550-b0adb8efa674.png)

I have checked that indeed, the numbers `3050` and `10230` are stored with an apostrophe in front (`'3050`).

So the issue is not restricted to tibbles. I consider this problematic because I don't seem to have any possibility to store those numbers as number in Excel. I understand the problem of the leading zeroes and trailing zeroes after the decimal mark that would be removed by Excel. But surely, Excel does not remove trailing zeroes that come *before* the decimal mark.

I would really appreciate it, if you would consider fixing this behaviour. If I can be of assistance, please let me know.

**Comment by marcschwartz** [comment]
Hi,

Thanks for the additional information.

The one thing that is common in each of the integer numbers that you have posted that were written as text, is that, in addition to the trailing 0s, there are 0s within the number as well, which you hint at. But there needs to be a particular sequence present.

There appears to be a need to have a non-zero integer within the sequence of 0s. So, '20000' does not trigger the behavior, but '20010' does.

I will take some time to look at this, as given this behavior, it suggests where the issue might be.

I appreciate the report, and will post back once I have a resolution and an incremental version ready to go to CRAN.

Thanks.

**Comment by thornend** [comment]
I know you are already working on fixing this, but thought it worth mentioning that I have also just encountered this after upgrading to WriteXLS 6.0.0.  I can also confirm that the following integers in an ordinary data frame are written as text:
0, 1010, 1020, 1040, 1050 etc. to 1090
Unfortunately this meant downgrading to 5.0.0 and re-running 1200 broken reports :-(
I look forward to trying the patched version.

**Comment by marcschwartz** [comment]
Hi,

Thanks for your comment. 

The pattern of the numbers that you have above is consistent with the sequences reported above.

I have some potential solutions, and will be working on this today.

**Comment by marcschwartz** [comment]
@stibu81 @thornend 

Hi, 

I have modified a relevant section of the Perl scripts to (hopefully) better handle leading and trailing zeros. I have also tested with the specific examples that you both provided, as well as adding examples to ?WriteXLS to test this behavior moving forward.

I am attaching here, what will become version 6.1.0, presuming that this resolves your issues. I am attaching both the source tarball and a Windows binary created using win-builder.

I have not yet committed the updates here, nor submitted to CRAN, pending further testing.

Please download and install the relevant file, and test these updates, at your convenience and let me know your findings.

Thanks!

[WriteXLS_6.1.0.tar.gz](https://github.com/marcschwartz/WriteXLS/files/5576233/WriteXLS_6.1.0.tar.gz)
[WriteXLS_6.1.0.zip](https://github.com/marcschwartz/WriteXLS/files/5576234/WriteXLS_6.1.0.zip)

**Comment by stibu81** [comment]
Hi @marcschwartz 

Thanks for the fixed package. I have tested the Linux version with my examples from above and some larger examples with many numbers of similar form and have not found a single one that was formatted as text. So this seems to be fixed.

I'm also going to check the code that made me originally discover the problem at work next week. 

Thanks for the very quick fix. I really appreciate this!

**Comment by stibu81** [comment]
Hi @marcschwartz 
I also checked the larger file that I was writing at work. This is an Excel file containing about 200'000 rows and in one column it had about 1'400 numbers formatted as text with WriteXLS 6.0.0. Those are all correctly formatted with version 6.1.0 and I could not find anything new that was off. So I am quite confident that the error is fixed. Thanks again!

**Comment by marcschwartz** [comment]
@stibu81 
Thanks for the updates, it is helpful to know that the issue appears to be resolved for you.

@thornend 
Will you have a chance to test the update to see if you can also confirm that the issue appears to be resolved for you?

Thanks to both of you.

**Comment by thornend** [comment]
@marcschwartz  
Thanks for the quick fix and sorry for the delay in responding.  I have just run a test, and found no problems with version 6.1.0.  The problem appears to have been fixed.

**Comment by marcschwartz** [comment]
@thornend 
No problem and I appreciate your confirmation that the issue appears to be resolved.

I will be submitting the 6.1.0 update to CRAN yet today.

Thanks again to both of you for the reports. I will be closing this issue.
