### ISSUE TITLE
WriteXLS 6.2.0 requires much more memory than 6.1.0

### ISSUE THREAD

**Issue by stibu81** [marcschwartz/WriteXLS#20]
Hi Mark

I have noticed that writing files with WriteXLS 6.2.0 uses much more memory than before with 6.1.0. Writing this data frame gives an Excel file of about 3 MB:

```
library(dplyr)
data <- tibble(
  col1 = paste("ABC", 100001:300000),
  col2 = paste(sample(1:1000, length(col1), replace = TRUE), "A")
)
WriteXLS(data, "test.xlsx")
```

Since the actual processing takes place in Perl, I have used `top` to look at the memory consumption of the `perl` process, which is of course not perfectly accurate. On my Machine with Ubuntu 20.04 and R 4.0.4, writing the Excel files uses about 260 MB of memory with WriteXLS 6.1.0, but 1.9 GB with WriteXLS 6.2.0. This is really an issue because it means that you need a strong and expensive Machine to write a small Excel-file.

Do you have an idea where this is coming from and whether it could be fixed?

Thanks and best regards
Stefan

**Comment by stibu81** [comment]
Thanks for looking into this. Since there were no decisive changes in 6.2.0, I can easily go on using 6.1.0 in the meantime.

**Comment by marcschwartz** [comment]
Hi Stefan,

With the kind assistance of the author of the Excel Perl packages, we have identified the issue, and I have created a new version, 6.3.0, of WriteXLS. 

I have tested it here, and it not only appears to resolve the issue, but I found that using the example data frame that you initially created, the memory utilization, at least on my Mac, is lower than with version 6.1.0. It is down to about 215 Mb, and the time is down to about 28 seconds.

I am attaching a source version of the new package tarball here, that should work on your Linux system, and would appreciate if you could run some preliminary testing on your system to confirm the resolution, before I submit the update to CRAN.

Please let me know what your experience with the new version is.

Thanks!

[WriteXLS_6.3.0.tar.gz](https://github.com/marcschwartz/WriteXLS/files/6240046/WriteXLS_6.3.0.tar.gz)

**Comment by stibu81** [comment]
Hi Mark,

This was quite fast for something that will take a bit... :-) Thanks! I have checked this and can confirm that memory consumption and time to write a file is back to about the level of 6.1.0. (My measurement is too crude to see any difference between 6.1.0 and 6.3.0, unfortunately.) So I consider this solved.

Thanks again for the very quick fix! WriteXLS is a very useful package for me and I appreciate the work you invest in it.

**Comment by marcschwartz** [comment]
Hi Stefan,

Have the expedient assistance of the Perl package author helped in rapidly tracking down the issue, without which, it likely would have taken far longer to resolve. 

I will be submitting version 6.3.0 to CRAN today, and it should start showing up on the CRAN mirrors in the coming days.

Thanks again for the report!
