### ISSUE TITLE
Exporting with Excel formulas

### ISSUE THREAD

**Issue by jamesfeigenbaum** [marcschwartz/WriteXLS#7]
Encountered a strange (semi) problem when exporting a data table with excel functions in it. If the formulas use capitalized excel cell notation ("B2") it works fine. But if the cells are called "b2" or "g3", the package complains about an "Unknown defined name SUM in formula at..." The error points to line 298 in WriteXLS.pl, but nothing there is obvious (to me).

The code below should recreate the problem. Isn't serious, but it took a while for me to catch that the upper and lower cases were my problem. (Then again, Excel auto-converts cases in cell references to upper and maybe no one else will get tripped up by this)

```
library(data.table)
library(WriteXLS)

DT = data.table(x=c("b","b","b","a","a"),v=rnorm(5))

DT[, test := "=SUM(B2:B3)"]

#this works
WriteXLS("DT", ExcelFileName = "test.xls")

DT[, test := "=SUM(b2:b3)"]

#this doesn't
WriteXLS("DT", ExcelFileName = "test.xls")
```

Best, 
James

(BTW, super useful package!)

**Comment by marcschwartz** [comment]
Hi James,

Thanks for your report and kind comment.

I can replicate the behavior using a regular data frame in base R, as opposed to using data.table.

That being said, based upon a search, the lowercase issue appears to be a limitation at some level of the older and no longer maintained Perl module Spreadsheet::WriteExcel, which is used in my package if you are creating an "XLS" file, as opposed to an "XLSX" file. 

In the latter case, the current Perl module Excel::Writer::XLSX is used and it does not appear to have the same issue. Both are from the same author and are included in WriteXLS. The current module is used in my Perl script, WriteXLSX.pl.

Example:

DF <- data.frame(x = c("b", "b", "b", "a", "a"), v = rnorm(5), test = "=SUM(b2:b3)")

# Use 'xlsx' as the file extension
WriteXLS("DF", "DF.xlsx")

No errors are reported in this case and the resultant XLSX file appears to be ok.

Thus, unless you have compatibility reasons to write an old XLS file format, I would recommend that you create XLSX files, to take advantage of newer and more robust functionality in the underlying Perl scripts and of course, the larger worksheet capacity.

I hope that is helpful.

Regards,

Marc

**Comment by jamesfeigenbaum** [comment]
Great Point Marc. This helps a lot and makes sense. In fact, switching to .xlsx from .xls sped up the entire exporting process, which was a nice benefit. Also, I suspect I'll be the only person to run into this issue because it requires one to be lazy enough to assign excel formulas in lower case *and* be using old .xls rather than .xlsx files.

Best,
James
